name: weekplanpro
description: "Una nueva aplicación Flutter para la planificación semanal."

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_time_picker_spinner: ^2.0.0
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  intl: ^0.18.1
  time_picker_spinner: ^0.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/logo_wpp.png
  uses-material-design: true
